export const FETCHING_PICTURE_LIST = 'FETCHING_PICTURE_LIST'
export const FETCHING_PICTURE_LIST_SUCCESS = 'FETCHING_PICTURE_LIST_SUCCESS'
export const FETCHING_PICTURE_LIST_FAILURE = 'FETCHING_PICTURE_LIST_FAILURE'

export const CREATE_PICTURE = 'CREATE_PICTURE'
export const CREATE_PICTURE_SUCCESS = 'CREATE_PICTURE_SUCCESS'
export const CREATE_PICTURE_FAILURE = 'CREATE_PICTURE_FAILURE'

export const CLEAN_PICTURE_DATA = 'CLEAN_PICTURE_DATA'